#!/usr/bin/env node
// lean-docs: keeps feature docs short, readable, portable and in step with the code. No dependencies, no AI.
//   lean-docs                                                 status: pages, coverage, stale docs, lint, in four lines
//   lean-docs [check] [--root .] [--keep-shape] <doc.md>...  fail docs that are bloated, unreadable, unportable or stale
//   lean-docs affected [--base <ref>] [--staged] [--strict] list docs whose code changed but the doc didn't
//   lean-docs index [dir]                                     print a table of every feature doc under dir
//   lean-docs coverage [dir] [--min <pct>]                    share of code files some doc covers, and the biggest gaps
//   lean-docs wiki [dir] [--out <dir>] [--format obsidian|notion] build the reader view of the pages for Confluence, Notion or a wiki
//   lean-docs relink [--record <publish.json>] <file>...     point page links at the published pages (second publishing pass)
//   lean-docs hook                                            Claude Code Stop hook: ask the agent once to update stale docs
import { readFileSync, writeFileSync, existsSync, realpathSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { resolve, join, basename, relative, sep, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';

// A link reference definition: hidden in CommonMark and, unlike an HTML comment, valid MDX (Docusaurus 3).
const INDEX_MARK = '[//]: # (generated by lean-docs index)';
const isIndex = (text) => text.startsWith(INDEX_MARK) || text.startsWith('<!-- generated by lean-docs index -->'); // old marker
// The same invisible line ties a guide that keeps its own shape to its code, with no Code section:
// [//]: # (lean-docs-code: src/client.py Timeout Client.send, src/config/)
const CODE_MARK = /^\[\/\/\]: # \(lean-docs-code:(.*)\)\s*$/;

const MAX_LINES = 60; // non-blank lines outside diagrams and the Use it example
const MAX_EXAMPLE = 15; // lines in one Use it code block
const MAX_WORDS = 30; // per sentence
const MAX_CODE_NAMES = 3; // backticked names in one prose line
const ALLOWED = ['how it works', 'use it', 'terms', 'config', 'does not', 'breaks when', 'code'];
const REQUIRED = ['how it works', 'does not', 'breaks when', 'code']; // affected reads Code

const BANNED = [
  [/\bthis (document|doc|page|guide|section|readme) (describes|explains|covers|provides|outlines|contains|introduces|shows|gives|is about|will|aims)\b/i, 'introduction, start with what it does'],
  [/\b(future (work|improvements|enhancements|plans)|roadmap|next steps)\b/i, 'future work, put it in an issue'],
  [/\b(in summary|in conclusion|to summarize|to sum up)\b/i, 'summary, the page is the summary'],
  [/\b(it is (important|worth) (to note|noting)|note that|please note|as mentioned)\b/i, 'throat-clearing'],
  [/\b(robust|seamless(ly)?|powerful|comprehensive|cutting-edge|state-of-the-art|leverag(e|es|ed|ing)|effortless(ly)?|simply|easily|elegant(ly)?|intuitive(ly)?|blazing(ly)?|streamlined?|scalable|flexible|best-in-class|world-class)\b/i, 'filler word'],
];

// Plain CommonMark + GFM tables + mermaid survives GitHub, GitLab, Confluence, Notion, Docusaurus, MkDocs.
const PORTABILITY = [
  [/<\/?[a-z][\w-]*(\s[^>]*)?\/?>/i, 'raw HTML, not portable'],
  [/^\s*(:::|!!!|\?\?\?)|^\s*>\s*\[!\w+\]/, 'admonition syntax, not portable, write a plain sentence'],
  [/\[\^[^\]]+\]/, 'footnote, not portable'],
  [/<(?=[^A-Za-z\/\s])|\{/, 'bare < or { outside backticks fails MDX (Docusaurus): wrap it in backticks'],
  // A link to a page in the same folder is fine: docs sites render it and publish.md rewrites it.
  [/\]\((?!https?:|mailto:|#)(?![\w.-]+\.mdx?(#[^)]*)?\))[^)]*\)/, 'relative link breaks outside the repo, write the path in backticks'],
];

// ponytail: naive split, "e.g." counts as a break. Errs toward shorter sentences, which is the point.
const sentences = (s) => s.split(/[.!?](?:\s|$)/).map((x) => x.trim()).filter(Boolean);
const words = (s) => s.split(/\s+/).filter(Boolean).length;

export function check(text, { root, keepShape, file } = {}) {
  if (file && /(^|\/)overview\.mdx?$/.test(file)) keepShape = true; // the landing page has its own shape
  const lines = text.replace(/\r\n?/g, '\n').split('\n'); // Windows line endings
  const problems = [];
  const add = (line, msg) => problems.push({ line, msg });
  const shape = (line, msg) => keepShape || add(line, msg);

  // YAML frontmatter (Docusaurus, MkDocs, Backstage) is allowed and not counted.
  if (lines[0] === '---') {
    const end = lines.indexOf('---', 1);
    if (end > 0) lines.fill('', 0, end + 1);
  }

  let fence = null;
  let table = null;
  let lead = null; // first paragraph after the title
  let section = null;
  let counted = 0;
  let examples = 0; // code blocks under Use it
  const diagrams = { flow: 0, sequence: 0 };
  const sections = new Set();
  const explained = new Set(); // sections holding a diagram or a numbered list

  const endTable = () => {
    // Code is read by affected, so it stays a table even with one row.
    if (table && table.rows <= 1 && table.section !== 'code') add(table.start, `table with ${table.rows} row, write it as a sentence`);
    table = null;
  };

  lines.forEach((l, i) => {
    const n = i + 1;
    const f = l.match(/^\s*(```|~~~)\s*([\w-]*)/);
    if (fence) {
      if (f && f[1] === fence.mark && !f[2]) {
        if (fence.lang === 'mermaid') {
          const kind = checkMermaid(fence.body, fence.line, add);
          if (kind) { diagrams[kind]++; explained.add(section); }
        } else if (section === 'use it' && !keepShape) {
          if (++examples === 2) add(fence.line, 'one example in "## Use it": the common case; other settings go in "## Config"');
          const size = fence.body.filter((b) => b.trim()).length;
          if (size > MAX_EXAMPLE) add(fence.line, `example is ${size} lines, max ${MAX_EXAMPLE}: show the common call, not every option`);
        }
        fence = null;
      } else {
        fence.body.push(l);
        if (fence.lang !== 'mermaid' && section !== 'use it' && l.trim()) counted++; // an example costs no reading time
      }
      return;
    }
    if (f) { endTable(); fence = { mark: f[1], lang: f[2].toLowerCase(), line: n, body: [] }; return; }
    if (CODE_MARK.test(l)) return; // invisible, not prose
    if (l.trim()) counted++;

    const isRow = /^\s*\|/.test(l);
    if (isRow) {
      table ??= { start: n, rows: 0, sep: false, section };
      if (/^[\s|:-]+$/.test(l) && l.includes('---')) table.sep = true;
      else if (table.sep) table.rows++;
    } else endTable();

    const h = l.match(/^(#{1,6})\s+(.*?)\s*#*\s*$/);
    if (h) {
      if (lead) lead.open = false;
      if (h[1].length === 1) return;
      const name = h[2].toLowerCase().replace(/[:.]$/, '');
      if (h[1].length === 2) {
        section = name;
        sections.add(name);
        if (!ALLOWED.includes(name)) shape(n, `section "${h[2]}" is not allowed (allowed: ${ALLOWED.join(', ')})`);
      } else shape(n, 'sub-heading, a one-page doc does not need them');
      return;
    }

    if (/^\s*\d+[.)]\s/.test(l)) explained.add(section);

    if (!lead && !sections.size && l.trim()) lead = { line: n, text: l, open: true };
    else if (lead?.open) l.trim() ? (lead.text += ' ' + l) : (lead.open = false);

    const prose = l.replace(/(`+)[\s\S]*?\1/g, 'x'); // code spans, including ``a `b` c``
    // Guides on a docs site (keep-shape) use its features: admonitions, HTML, links between pages.
    // Feature pages get copied to Confluence and Notion, so they can't.
    const unquoted = prose.replace(/"[^"]*"|“[^”]*”/g, 'x'); // a quoted phrase is a mention, not a use
    for (const [re, msg] of [...BANNED, ...(keepShape ? [] : PORTABILITY)]) {
      const m = (/^(raw HTML|relative link|bare)/.test(msg) ? prose : unquoted).match(re);
      if (m) add(n, `${msg} ("${m[0]}")`);
    }

    // Readability: tables and the Code section are reference, not prose.
    if (!isRow && section !== 'code') {
      const long = sentences(prose.replace(/^\s*([-*]|\d+[.)])\s+/, '')).find((s) => words(s) > MAX_WORDS);
      if (long) add(n, `${words(long)}-word sentence, max ${MAX_WORDS}: split it`);
      // Per sentence, as page.md says: a paragraph is one line, so counting per line punishes paragraphs.
      // A URL, a URL path (`/items/{id}`) or a status code (`307`) is an address or a value, not a code name.
      const names = Math.max(0, ...sentences(l.replace(/(`+)([\s\S]*?)\1/g, (m, q, c) => (/^\s*(https?:\/\/\S+|\/[\w.~{}:*\/-]*|\d{3})\s*$/.test(c) ? 'x' : '\u0000'))).map((t) => (t.match(/\u0000/g) || []).length));
      if (names > MAX_CODE_NAMES && !keepShape) add(n, `${names} code names in one sentence: say it in words, put the names in "## Code"`); // API guides list names
    }

    if (!keepShape && /`[\w.@\/-]+\.\w+:\d+(-\d+)?`/.test(l)) add(n, 'line numbers drift: name the file and the function instead');

    // A relative link that points at nothing (guides on a docs site may link to each other).
    if (root && file) {
      for (const [, href] of prose.matchAll(/\]\((?!https?:|mailto:|#)([^)\s]+)\)/g)) {
        const target = resolve(dirname(resolve(file)), decodeURIComponent(href.split('#')[0]));
        if (href.split('#')[0] && !existsSync(target)) add(n, `link to ${href} points at nothing`);
      }
    }

    if (root && !keepShape) { // guides name files in other repos and files the reader creates
      // ponytail: anything like `a/b.ext` is treated as a repo path; MIME types like `application/x.y` false-positive.
      for (const [, p] of l.matchAll(/`([\w.@-]+(?:\/[\w.@-]+)*\/[\w@-]+\.\w+)`/g)) {
        if (!existsSync(resolve(root, p))) add(n, `\`${p}\` does not exist, the doc is stale or invented`);
      }
    }
  });
  endTable();

  // A symbol named in a Code row that isn't in its file was renamed or misspelled. affected would
  // never flag the page for it again, so say so now.
  if (root) {
    for (const { path, symbols, marker, fromWhat = [] } of codeRows(text)) {
      const file = resolve(root, path);
      if (marker && !existsSync(file)) add(0, `\`${path}\` in the lean-docs-code line does not exist: moved or renamed?`);
      if (!symbols.length || !existsSync(file) || path.endsWith('/')) continue;
      let src = '';
      try { src = readFileSync(file, 'utf8'); } catch { continue; }
      for (const sym of symbols.filter((s) => !fromWhat.includes(s))) {
        if (!new RegExp('\\b' + escapeRe(sym) + '\\b').test(src)) add(0, `\`${sym}\` isn't in ${path}: renamed? This page won't go stale when that code changes`);
      }
    }
  }

  if (!keepShape) {
    // A file under a folder row is already covered by it; the extra row is noise.
    const rows = codeRows(text).map((r) => r.path);
    for (const p of rows) {
      const dir = rows.find((d) => d !== p && d.endsWith('/') && p.startsWith(d));
      if (dir) add(0, `\`${p}\` is inside \`${dir}\`, already in "## Code": drop one row`);
    }
    if (counted > MAX_LINES) add(0, `${counted} lines (diagrams not counted), max ${MAX_LINES}. If it needs a second page, it is two features.`);
    if (lead) {
      const count = sentences(lead.text).length;
      if (count > 2) add(lead.line, `opening is ${count} sentences, max 2`);
      const names = (lead.text.match(/`[^`]+`/g) || []).length;
      if (names > 1) add(lead.line, `opening has ${names} code names, max 1: say what it does in plain words`);
    } else add(0, 'missing an opening: one or two plain sentences under the title');
    for (const s of REQUIRED) if (!sections.has(s)) add(0, `missing "## ${s[0].toUpperCase() + s.slice(1)}" section`);
    if (sections.has('how it works') && !explained.has('how it works'))
      add(0, '"## How it works" needs a mermaid diagram, or numbered steps if there are three or fewer');
    if (diagrams.flow > 1 || diagrams.sequence > 1) add(0, 'more than one diagram of a kind: one flow, one sequence at most');
  }

  return problems.sort((a, b) => a.line - b.line);
}

const ARROW = /\s*(?:<?-->|<?==>|<?-\.->|---|--[^->|]+?-->|==[^=>]+?==>|-\.[^.]+?\.->)(?:\|[^|]*\|)?\s*/;

// Returns 'flow' or 'sequence' for a diagram worth drawing, null otherwise.
function checkMermaid(body, line, add) {
  const type = (body.find((l) => l.trim()) || '').trim().split(/\s/)[0];

  if (type === 'sequenceDiagram') {
    const msgs = body
      .map((l) => l.match(/^\s*([\w ]+?)\s*(?:--?>>|--?>|--?[x)])[+-]?\s*([\w ]+?)\s*:/))
      .filter(Boolean)
      .map((m) => [m[1].trim(), m[2].trim()]);
    const pairs = new Set(msgs.map(([a, b]) => `${a}>${b}`));
    const backAndForth = msgs.some(([a, b]) => a !== b && pairs.has(`${b}>${a}`));
    if (msgs.length >= 3 && backAndForth) return 'sequence';
    add(line, 'sequence diagram with no real back-and-forth, use a flowchart or a sentence');
    return null;
  }

  if (type !== 'flowchart' && type !== 'graph') {
    add(line, `"${type}" diagram, only flowchart and sequenceDiagram are allowed`);
    return null;
  }

  // GitHub's mermaid fails the whole diagram on ( ) inside an unquoted box label: A[call foo(x)].
  const box = /([\w-]+)(?:\[([^\]"]*[()][^\]]*)\]|\{([^}"]*[()][^}]*)\})/;
  const bad = body.map((l) => l.match(box)).find(Boolean);
  if (bad) add(line, `unquoted ( ) in a box label breaks the diagram on GitHub: write ${bad[1]}${bad[2] !== undefined ? `["${bad[2]}"]` : `{"${bad[3]}"}`}`);
  // Same for quotes inside edge text: A -- say "x" --> B, or A -->|say "x"| B.
  // A label is fine with no quotes, or fully wrapped in one pair of quotes.
  const badLabel = (t) => t.includes('"') && !/^"[^"]*"$/.test(t.trim());
  const badEdge = body.find((l) => [...l.matchAll(/--\s+([^>|]+?)\s+-->|\|([^|]*)\|/g)].some((m) => badLabel(m[1] ?? m[2])));
  if (badEdge) add(line, `quotes inside an edge label break the diagram on GitHub: use -->|"label"| with no quotes inside (${badEdge.trim().slice(0, 40)})`);

  const nodes = new Set();
  for (const l of body) {
    if (l.trim().startsWith('%%')) continue;
    const ids = l.split(ARROW).map((p) => p.trim().match(/^([\w-]+)/)?.[1]).filter(Boolean);
    if (ids.length >= 2) ids.forEach((id) => nodes.add(id));
  }
  if (nodes.size >= 3) return 'flow';
  add(line, `flow diagram with ${nodes.size} boxes, write one sentence`);
  return null;
}

// Paths a doc says it covers: backticked file or folder paths in its "## Code" section.
export function codePaths(text) {
  return [...new Set(codeRows(text).map((r) => r.path))];
}

// A path has a slash or a file extension. `Client.send` and `Type::method` are symbols, not paths.
const FILE_EXT = /\.(js|jsx|ts|tsx|mjs|cjs|py|go|rb|java|kt|rs|php|cs|swift|scala|c|cc|cpp|h|hpp|ex|exs|dart|vue|svelte|md|mdx|json|ya?ml|toml|txt|lock|html|css|scss|sh|sql|proto|graphql|env|tf|ini|cfg|xml|gradle)$/i;
const isPath = (t) => t.includes('/') || FILE_EXT.test(t);
// `SearchWorker::search`, `Client.send`, `Foo#bar` are matched by their last part, the name in the code.
const symbolName = (t) => t.replace(/\(\)$/, '').split(/::|\.|#/).pop();

// Rows of the "## Code" section: a path, plus any functions or classes named in the same cell
// ("`src/client.py` `send`, `retry`"). With symbols, only changes to those symbols make the page stale.
// "- `path` `sym`: what it does" → "- `path` `sym`". Cuts at the first ": " outside backticks.
function whereOfListItem(l) {
  let inCode = false;
  for (let i = 0; i < l.length; i++) {
    if (l[i] === '`') inCode = !inCode;
    else if (!inCode && l[i] === ':' && (l[i + 1] === ' ' || i === l.length - 1)) return l.slice(0, i);
  }
  return l;
}

export function codeRows(text) {
  // A "## Code" inside a code fence (a page template, an example) isn't this page's Code section.
  const lines = text.replace(/\r\n?/g, '\n').replace(/^(`{3,}|~{3,})[^\n]*\n[\s\S]*?^\1\s*$/gm, '').split('\n');
  const rows = [];
  const add = (tokens, extra, what = []) => {
    tokens = tokens.map((t) => t.replace(/:\d+(-\d+)?$/, '').replace(/^\.\//, ''));
    const symbols = tokens.filter((t) => !isPath(t)).map(symbolName).filter(Boolean);
    // A row naming functions also counts the ones only its What names: agents copy just the first few
    // into Where. check doesn't hold What to that (it can name a field or a type from elsewhere).
    const fromWhat = symbols.length ? [...new Set(what.filter((t) => !isPath(t) && /^[A-Za-z_$][\w$]*((::|\.|#)[\w$]+)*(\(\))?$/.test(t)).map(symbolName))].filter((t) => !symbols.includes(t)) : [];
    for (const path of tokens.filter(isPath)) rows.push({ path, symbols: [...symbols, ...fromWhat], ...extra, ...(fromWhat.length && { fromWhat }) });
  };
  const start = lines.findIndex((l) => /^##\s+code\s*$/i.test(l));
  const end = lines.findIndex((l, i) => i > start && /^##\s/.test(l));
  for (const l of start < 0 ? [] : lines.slice(start + 1, end < 0 ? undefined : end)) {
    const table = l.trim().startsWith('|'), cell = table ? l.split('|')[1] : whereOfListItem(l); // the "Where" part
    const ticked = (t) => [...t.matchAll(/`([^`\s]+)`/g)].map((m) => m[1]);
    add(ticked(cell), undefined, ticked(table ? l.split('|')[2] ?? '' : l.slice(cell.length)));
  }
  // Each comma-separated item of a lean-docs-code line is a path and its symbols, backticks optional.
  for (const l of lines) {
    const m = l.match(CODE_MARK);
    if (m) for (const item of m[1].split(',')) add(item.replace(/`/g, ' ').split(/\s+/).filter(Boolean), { marker: true });
  }
  return rows;
}

// A feature page has a Code section; a guide tied to code only by a lean-docs-code line keeps its shape.
const isGuide = (rows) => rows.length > 0 && rows.every((r) => r.marker);

const covers = (path, file) => file === path || file.startsWith(path.endsWith('/') ? path : path + '/');

// Docs whose covered code changed while the doc itself did not.
// `ok` holds docs a commit marked as checked ("lean-docs-ok: <doc>" or "lean-docs-ok: all").
const escapeRe = (t) => t.replace(/[.*+?^$()|[\]\\{}]/g, '\\$&');

// A call doesn't change what a page says about a name, so `send(`, `x.send` and `send.x` don't count,
// unless they are on a hunk's first line or its first line past a doc comment (the enclosing function
// or statement), or follow a definition keyword (`def send(`). Any other mention does: `send =`, `has_many :send`, a comment.
// Nor does a parameter or a labelled argument of that name (`(_ send: Msg)`, `for: send,`), even on a
// first line; a key holding a function (`send: () =>`), a Ruby `:send` and a declared property
// (`(val send: Int)`, `(private send: T)`) still count.
// ponytail: Ruby's paren-less calls (`send << x`), Python kwargs (`send=x`) and bare arguments (`f(a, send)`)
// still count: an isinstance(x, Timeout) in Timeout's own method was a real flag.
const DEF = '\\b(def|fun|func|fn|function|class|val|var|let|const|sub|module|struct|enum|interface|type|trait|object)\\s+(\\([^)]*\\)\\s*)?[*&]?([\\w$]+\\.)?';
// A name taken from a What cell (`fromWhat`) only counts as the enclosing function (the first line of a
// hunk past its doc comment) or after a definition keyword: What also holds example values like `a.b`.
const defines = (diff, sym, fromWhat) => {
  const s = escapeRe(sym), word = new RegExp('\\b' + s + '\\b');
  diff = diff.replace(new RegExp('([(,]\\s*(?:(?!(?:val|var|let|const|private|public|protected|internal|readonly|override|open|final)\\b)\\w+\\s+)?)' + s + '(?=\\s*:(?!:))(?!\\s*:\\s*(?:async\\b|function\\b|\\())|(\\w:\\s*)' + s + '(?=\\s*[,)])', 'g'), '$1$2 ');
  const hunks = diff.split(/^@@.*\n/m).slice(1).map((h) => h.split('\n'));
  // C, Java: `int send(` follows its doc comment; Dart, Java: `void send(` follows `@override`.
  const fn = (h) => h.find((l) => !/^.\s*(\/\/|\/\*|\*|#|@[\w.]+(\(.*\))?\s*$|$)/.test(l)) ?? '';
  if (fromWhat) return hunks.some((h) => word.test(fn(h))) || new RegExp(DEF + s + '\\b').test(diff);
  const firsts = hunks.flatMap((h) => [h[0], fn(h)]);
  const notCalls = diff.replace(new RegExp('(\\.|::|->)\\s*' + s + '\\b|\\b' + s + '\\s*[(.]', 'g'), ' ');
  return firsts.some((l) => word.test(l)) || new RegExp(DEF + s + '\\b').test(diff) || word.test(notCalls);
};

// A flag is likely real when the changed lines share a camelCase or snake_case name, a string or a number
// of 2+ digits with the page outside its Code section; otherwise it is a "check". On 30 Cobra commits the
// likely ones were 11 real of 22 and the checks 2 of 45. Both still count as stale.
// ponytail: a word match, not a parser; plain lowercase names (`args`, `path`) match prose, so they don't count.
// A changed line that mentions deprecation (`@deprecated use y`) is likely too: readers need it, and it rarely shares a name.
// ponytail: any /deprecat/i on a changed line, so un-deprecating or a typo fix in such a comment also counts; parse the tag if that gets noisy.
const STR = /"((?:[^"\\\n]|\\.)*)"|'((?:[^'\\\n]|\\.)*)'/g;
function shares(text, code) {
  if (/deprecat/i.test(code)) return true;
  const ls = text.split('\n'), s = ls.findIndex((l) => /^##\s+code\s*$/i.test(l)), e = ls.findIndex((l, i) => i > s && /^##\s/.test(l));
  const page = (s < 0 ? ls : [...ls.slice(0, s), ...(e < 0 ? [] : ls.slice(e))]).filter((l) => !CODE_MARK.test(l)).join('\n');
  if ([...code.matchAll(STR)].some((m) => (m[1] ?? m[2]).replace(/%\w|\\./g, '').trim().length >= 3 && page.includes(m[1] ?? m[2]))) return true;
  code = code.replace(STR, ' ');
  const nums = (code.match(/\b\d+(\.\d+)?\b/g) ?? []).filter((n) => n.length >= 2);
  const names = (code.match(/[A-Za-z_$][\w$]{2,}/g) ?? []).filter((t) => /[a-z0-9][A-Z]|_\w/.test(t));
  return nums.some((n) => new RegExp('(?<![\\w.])' + escapeRe(n) + '(?![\\w.])').test(page))
    || names.some((t) => new RegExp('(?<![\\w$])' + escapeRe(t) + '(?![\\w$])').test(page));
}

// `diffOf(file)` returns the change to a file with whole-function context, or null when it was only
// reformatted or had comments edited; rows that name symbols only count when it mentions one of them other than as a call.
export function affected(docs, changed, ok = new Set(), diffOf = () => '') {
  const touched = new Set(changed);
  const changedSyms = (row, file) => row.symbols.filter((sym) => defines(diffOf(file), sym, row.fromWhat?.includes(sym)));
  const hits = (row, file) => covers(row.path, file) && diffOf(file) !== null && (!row.symbols.length || changedSyms(row, file).length > 0);
  return docs
    .filter((d) => !touched.has(d.file) && !ok.has(d.file) && !ok.has('all'))
    .map((d) => {
      const rows = d.rows ?? d.paths.map((path) => ({ path, symbols: [] }));
      const because = changed.filter((c) => rows.some((r) => hits(r, c)));
      // Which named functions changed, so the reader knows which part of the page to fix.
      // A row without symbols covers the whole file, so then there's nothing narrower to say.
      const symbols = {};
      for (const f of because) {
        const matched = rows.filter((r) => hits(r, f));
        if (!matched.every((r) => r.symbols.length)) continue;
        const inContext = [...new Set(matched.flatMap((r) => changedSyms(r, f)))];
        // Prefer names on the changed lines themselves; the surrounding context can hold neighbours.
        const edited = diffOf(f).split('\n').filter((l) => /^[-+]/.test(l)).join('\n');
        const direct = inContext.filter((sym) => new RegExp('\\b' + escapeRe(sym) + '\\b').test(edited));
        symbols[f] = direct.length ? direct : inContext;
      }
      const r = Object.keys(symbols).length ? { file: d.file, because, symbols } : { file: d.file, because };
      if (typeof d.text === 'string') r.likely = shares(d.text, because.flatMap((f) => {
        const diff = diffOf(f) ?? '', mine = rows.filter((row) => hits(row, f));
        if (!diff.includes('@@')) return [diff]; // a new file counts in full
        return diff.split(/^(?=@@)/m).filter((h) => mine.some((row) => !row.symbols.length || row.symbols.some((sym) => defines(h, sym, row.fromWhat?.includes(sym)))))
          .map((h) => h.split('\n').filter(isChange).map((l) => l.slice(1)).join('\n'));
      }).join('\n'));
      return r;
    })
    .filter((d) => d.because.length);
}

const git = (args, cwd) => {
  // quotePath=false: otherwise git prints "caf\303\251.ts" for café.ts and no path would match.
  // The default 1 MB output cap fails on big repos: Next.js lists 34,000 files in 2.4 MB.
  try { return execFileSync('git', ['-c', 'core.quotePath=false', ...args], { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 1 << 30 }); }
  catch { throw new Error(`git ${args.join(' ')} failed`); }
};
const lines = (s) => s.split('\n').filter(Boolean);
const files_ = (n) => `${n} code file${n === 1 ? '' : 's'}`;

function branchBase(cwd, base) {
  if (base) return base;
  for (const ref of ['origin/HEAD', 'origin/main', 'origin/master', 'main', 'master']) {
    try { return git(['merge-base', 'HEAD', ref], cwd).trim(); } catch {}
  }
}
// HEAD, or the empty tree in a repo with no commits yet, so every file counts as new.
function tip(cwd) {
  try { git(['rev-parse', '--verify', '-q', 'HEAD'], cwd); return 'HEAD'; } catch { return git(['hash-object', '-t', 'tree', '--stdin'], cwd).trim(); }
}

// The change to one file, with the whole enclosing function as context, minus git's header
// (its "index abc..def" line would match a symbol called index). New files count in full.
// git's built-in function finders, which only switch on through attributes. Without them a change
// inside a Python method has the whole class as its "function", so every method name in it matches.
const DRIVERS = { py: 'python', go: 'golang', rs: 'rust', java: 'java', kt: 'kotlin', rb: 'ruby', php: 'php',
  cs: 'csharp', c: 'cpp', cc: 'cpp', cpp: 'cpp', cxx: 'cpp', h: 'cpp', hh: 'cpp', hpp: 'cpp', ex: 'elixir', exs: 'elixir',
  m: 'objc', mm: 'objc', pl: 'perl', swift: 'leanswift', dart: 'leandart' };
// git has no JavaScript/TypeScript finder, so here is one: functions, classes, methods, getters,
// and arrow functions in consts or class fields. Lines starting with a keyword are never boundaries.
const JS_FUNCNAME = [
  '!^[ \t]*(if|for|while|switch|catch|return|else|do|try|with|new|throw|await|yield)[ \t(]',
  '^[ \t]*((export[ \t]+)?(default[ \t]+)?(async[ \t]+)?function[ \t*]*[A-Za-z0-9_$]*[ \t]*[(<].*)$',
  '^[ \t]*((export[ \t]+)?(default[ \t]+)?(abstract[ \t]+)?class[ \t]+[A-Za-z0-9_$]+.*)$',
  '^[ \t]*((export[ \t]+)?(const|let|var)[ \t]+[A-Za-z0-9_$]+[ \t]*(:[^=]*)?=[ \t]*(async[ \t]+)?(\\(|[A-Za-z0-9_$]+[ \t]*=>|function).*)$',
  '^[ \t]*(((public|private|protected|static|readonly|override)[ \t]+)*[A-Za-z0-9_$#]+[ \t]*(:[^=]*)?=[ \t]*(async[ \t]+)?\\(.*=>.*)$',
  '^[ \t]*(((public|private|protected|static|readonly|async|override|get|set)[ \t]+)*[A-Za-z0-9_$#]+[ \t]*(<[^>]*>)?[ \t]*\\([^;]*\\)[ \t]*(:[^;{]*)?\\{[ \t]*)$',
].join('\n');
// Nor a Swift one, and git's default only finds column-0 lines, so an edit in any method of a class
// or extension had the whole type as its context: declarations (indented ones too) and computed properties.
const SWIFT_FUNCNAME = [
  '!^[ \t]*(if|guard|for|while|repeat|switch|case|default|return|else|do|catch|defer|throw|try|await)([ \t({:]|$)',
  '^[ \t]*((@[A-Za-z_]+(\\([^)]*\\))?[ \t]+)*([a-z]+(\\([a-z]+\\))?[ \t]+)*(func|init|deinit|subscript|class|struct|enum|extension|protocol|actor)([ \t?!<({].*)?)$',
  '^[ \t]*((@[A-Za-z_]+[ \t]+)*([a-z]+(\\([a-z]+\\))?[ \t]+)*(var|let)[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*:[^={]*\\{[ \t]*)$',
].join('\n');
// Nor a Dart one. dart format puts class members at exactly 2 spaces and Dart has no nested classes,
// so a declaration is a line at column 0 or 2: a type, a getter/setter/operator, a typed function or
// method, or a constructor. Statements, parameter lines (ending in `,`) and `x =` lines are not.
// ponytail: a 2-space `Foo.bar(` call inside a top-level function also counts as a boundary.
const DART_FUNCNAME = [
  '!^[ \t]*(if|for|while|switch|case|default|return|else|do|try|catch|finally|on|throw|await|yield|assert|new|break|continue)([ \t({:;]|$)',
  '!(,|=)[ \t]*$',
  '^((abstract |sealed |base |final |interface |mixin )*(class|mixin|extension|enum|typedef)[ \t].*)$',
  '^( {0,2}[A-Za-z_][]A-Za-z0-9_<>?,.[ ]*[ \t]+(get|set|operator)[ \t]+.*)$',
  '^( {0,2}([A-Za-z_][]A-Za-z0-9_<>?,.[ ]*[ \t]+)[A-Za-z_$][A-Za-z0-9_$]*(<[^>]*>)?\\(.*)$',
  '^( {0,2}((const|factory|external)[ \t]+)*[A-Z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)?\\(.*)$',
].join('\n');

let attributesFile;
function driverAttributes() {
  if (!attributesFile) {
    attributesFile = join(tmpdir(), 'lean-docs-diff-drivers');
    const js = ['js', 'jsx', 'ts', 'tsx', 'mjs', 'cjs'].map((ext) => `*.${ext} diff=leanjs`);
    writeFileSync(attributesFile, [...Object.entries(DRIVERS).map(([ext, d]) => `*.${ext} diff=${d}`), ...js].join('\n') + '\n');
  }
  return attributesFile;
}

// git's --function-context reaches back to the last function line, so a change to a top-level const
// or an `if __name__` block pulled in the whole function above it. Each hunk now starts at the
// top-level statement holding its first change: a column-0 line after a blank line.
// ponytail: a column-0 line after a blank inside a multi-line string also counts as a start.
const fromChange = (diff) => diff.split(/^(?=@@)/m).map((hunk) => {
  const ls = hunk.split('\n');
  const first = ls.findIndex((l) => /^[-+]/.test(l));
  for (let i = first; i > 1; i--) if (/^.[A-Za-z_@#/]/.test(ls[i]) && /^.?\s*$/.test(ls[i - 1])) return [ls[0], ...inBlock(ls.slice(i))].join('\n');
  return [ls[0], ...inBlock(ls.slice(1))].join('\n');
}).join('\n'); // inBlock can drop a hunk's last newline; the next @@ must start a line

// A CLI keeps its commands in one block (`if (main) {`, `if __name__ == '__main__':`). git's function
// context for an edit there starts anywhere in that block, even at a blank line, and runs to its end, so
// every command's page matched. Inside a block, keep only the statements holding a change; a lone
// top-level `if`/`for`/... is unwrapped first. Comments and decorators belong to the statement below
// them; a line opening with `}`, `)`, `except` or `end` continues the one above, while `elif` starts its own.
// ponytail: indentation stands in for parsing; a multi-line string at column 0 turns it off.
const indent = (l) => l.slice(1).match(/^\s*/)[0].length;
const blank = (l) => !l.slice(1).trim();
const goesOn = (l) => /^.\s*([}\])]|(except|finally|rescue|ensure|catch|end)\b)/.test(l);
const isChange = (l) => /^[-+]/.test(l);
function inBlock(ls) {
  const heads = ls.filter((l) => !blank(l) && !goesOn(l));
  if (!heads.length) return ls;
  const top = Math.min(...heads.map(indent));
  const parts = [];
  let prefix = false;
  for (const l of ls) {
    if (!parts.length || (!blank(l) && !goesOn(l) && indent(l) === top && !prefix)) parts.push([]);
    parts.at(-1).push(l);
    if (!blank(l)) prefix = indent(l) === top && /^.\s*(@|#|\/\/|\/\*|\*)/.test(l);
  }
  if (top > 0) return parts.filter((p) => p.some(isChange)).flat();
  if (parts.filter((p) => p.some((l) => !blank(l))).length > 1) return ls;
  const h = ls.findIndex((l) => /^.(if|for|while|try|switch|with|do|unless)\b/.test(l));
  return h < 0 || ls.slice(0, h + 1).some(isChange) ? ls : [...ls.slice(0, h + 1), ...inBlock(ls.slice(h + 1))];
}

// A hunk that only re-indents or re-wraps code, or only edits comments, doesn't change what a page says,
// unless it deprecates something (`@deprecated` in a JSDoc is a real change). In Python only spacing
// inside a line can change, since indentation is code there. The old side (context and '-' lines) is
// compared with the new side (context and '+' lines), so a statement moved past an unchanged line counts.
// ponytail: a line guess, not a parser; a code line inside a block comment, a string starting with `* `
// or spaces inside a string literal count as cosmetic. `#` is a comment only before a space or `#`
// (keeps `#define`, `#[derive]`).
const COMMENT = /^\s*(\/\/|\/\*|\*\/|\*(\s|$)|#(\s|$|#))/;
function cosmetic(hunk, py) {
  const code = hunk.split('\n').slice(1).filter((l) => /^[-+ ]/.test(l) && l.slice(1).trim());
  if (code.some((l) => isChange(l) && /deprecat/i.test(l))) return false;
  const side = (sign) => code.filter((l) => l[0] !== sign && !COMMENT.test(l.slice(1))).map((l) => (py ? l.slice(1).match(/^\s*/)[0] : '') + l.slice(1).replace(/\s/g, '')).join(py ? '\n' : '');
  return side('+') === side('-');
}

// Python: git's function finder also matches a `def` inside a docstring's example code, so an edit in
// `include_router` was credited to `read_users` from its docstring, and the page naming include_router
// stayed quiet. Find the real enclosing def or class ourselves, skipping triple-quoted strings, and put
// it on the hunk's first line, which is where `defines` looks for the enclosing function.
export function pythonEnclosing(src, lineNo) {
  const ls = src.split('\n');
  // One pass over logical lines: a line starts a statement only outside strings and brackets.
  let quote = null, depth = 0;
  const starts = [], defs = [];
  ls.forEach((l, i) => {
    const starting = !quote && depth === 0;
    const ind = l.match(/^\s*/)[0].length;
    if (starting && l.trim() && !/^\s*#/.test(l)) {
      starts.push({ i, ind });
      const m = l.match(/^(\s*)(async\s+def|def|class)\s+\w/);
      if (m) defs.push({ i, ind, text: l });
    }
    // Strip strings and comments before counting brackets; a triple quote opens or closes a string across lines.
    let rest = l;
    while (rest) {
      if (quote) {
        const at = rest.indexOf(quote);
        if (at < 0) { rest = ''; break; }
        rest = rest.slice(at + 3); quote = null; continue;
      }
      const m = rest.match(/"""|'''|(["'])(?:\\.|(?!\1).)*\1|#.*|[()[\]{}]/);
      if (!m) break;
      if (m[0] === '"""' || m[0] === "'''") quote = m[0];
      else if ('([{'.includes(m[0])) depth++;
      else if (')]}'.includes(m[0])) depth = Math.max(0, depth - 1);
      rest = rest.slice(m.index + m[0].length);
    }
  });
  // A def's block runs to the line before the next statement indented no deeper than the def itself.
  for (const d of defs) {
    const next = starts.find((s) => s.i > d.i && s.ind <= d.ind && !/^\s*(\)|\]|\})/.test(ls[s.i]));
    d.end = next ? next.i - 1 : ls.length - 1;
  }
  const t = lineNo - 1;
  return defs.filter((d) => d.i <= t && t <= d.end).pop()?.text ?? null;
}
function withPythonDefs(d, src) {
  if (!src) return d;
  return d.split(/^(?=@@)/m).map((h) => {
    const m = h.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
    if (!m) return h;
    const ls = h.split('\n');
    let n = +m[1] - 1, first = null;
    for (const l of ls.slice(1)) { if (l.startsWith('-')) { first ??= n + 1; continue; } n++; if (l.startsWith('+')) { first ??= n; break; } }
    const def = first && pythonEnclosing(src, first);
    return def && ls[1]?.slice(1) !== def ? [ls[0], ' ' + def, ...ls.slice(1)].join('\n') : h;
  }).join('');
}

function differ(cwd, { base, staged }) {
  const cache = new Map();
  const range = staged ? ['--cached'] : [branchBase(cwd, base) || tip(cwd)];
  return (file) => {
    if (!cache.has(file)) {
      let d = '';
      // Hunk headers name the function *before* the hunk, so they're dropped; --function-context already has the real one.
      try { d = git(['-c', `core.attributesFile=${driverAttributes()}`, '-c', `diff.leanjs.xfuncname=${JS_FUNCNAME}`, '-c', `diff.leanswift.xfuncname=${SWIFT_FUNCNAME}`, '-c', `diff.leandart.xfuncname=${DART_FUNCNAME}`, 'diff', '--function-context', ...range, '--', file], cwd).replace(/^(diff --git|index |--- |\+\+\+ ).*$/gm, '').replace(/^(@@[^@]*@@).*$/gm, '$1'); } catch {}
      // git gave a diff but every hunk was cosmetic: null, the file counts as unchanged (not as a new file to read whole).
      const gave = d.trim();
      d = d.split(/^(?=@@)/m).filter((h) => !h.startsWith('@@') || !CODE.test(file) || !cosmetic(h, file.endsWith('.py'))).join('');
      if (file.endsWith('.py') && d.trim()) {
        let src = '';
        try { src = staged ? git(['show', `:${file}`], cwd) : readFileSync(join(cwd, file), 'utf8'); } catch {}
        d = withPythonDefs(d, src);
      }
      d = fromChange(d);
      if (gave && !d.trim()) d = null;
      else if (!d.trim() && existsSync(join(cwd, file))) { try { d = readFileSync(join(cwd, file), 'utf8'); } catch {} }
      cache.set(file, d);
    }
    return cache.get(file);
  };
}

// "R100\told\tnew", "D\tpath", "M\tpath" → every path involved, plus a note for renames and deletions.
// --name-only would list only the new name of a renamed file, so pages covering the old one went unflagged.
export function parseNameStatus(text) {
  const files = [];
  const notes = new Map();
  for (const l of lines(text)) {
    const [status, a, b] = l.split('\t');
    if (status.startsWith('R') && b) { files.push(a, b); notes.set(a, `renamed to ${b}`); }
    else if (status === 'D') { files.push(a); notes.set(a, 'deleted'); }
    else if (a) files.push(a);
  }
  return { files, notes };
}

function changedFiles(cwd, { base, staged }) {
  const range = staged ? ['--cached'] : [branchBase(cwd, base) || tip(cwd)];
  const { files, notes } = parseNameStatus(git(['diff', '--name-status', '-M', ...range], cwd));
  const all = [...new Set([...files, ...(staged ? [] : lines(git(['ls-files', '-o', '--exclude-standard'], cwd)))])];
  all.notes = notes;
  return all;
}

const noted = (changed, f) => (changed.notes?.get(f) ? `${f} ${changed.notes.get(f)}` : f);
// "src/a.ts: send; src/b.ts": each changed file, with the functions that changed when the page names them.
const CHECK = ' (check: no changed name or string is in the doc)';
const byLikely = (stale) => [...stale.filter((d) => d.likely), ...stale.filter((d) => !d.likely)];
const why = (changed, d) => d.because.map((f) => noted(changed, f) + (d.symbols?.[f]?.length ? `: ${d.symbols[f].join(', ')}` : '')).join('; ');

// Commit trailers on this branch saying a doc was checked and is still right.
export function reviewedIn(messages) {
  const ok = new Set();
  for (const [, list] of messages.matchAll(/^lean-docs-ok:\s*(.+)$/gim)) list.split(/[\s,]+/).filter(Boolean).forEach((d) => ok.add(d));
  return ok;
}

function reviewed(cwd, base) {
  base = branchBase(cwd, base);
  if (!base) return new Set();
  try { return reviewedIn(git(['log', `${base}..HEAD`, '--format=%B'], cwd)); } catch { return new Set(); }
}

// Docusaurus and others use .mdx for pages.
const DOC_GLOBS = ['*.md', '*.mdx'];

// Example, test and fixture folders hold sample docs for other repos, not this repo's pages.
const NOT_DOCS = /(^|\/)(examples?|evals?|fixtures?|tests?|__tests__|node_modules|vendor)\//;

function repoDocs(cwd) {
  return lines(git(['ls-files', '-co', '--exclude-standard', ...DOC_GLOBS], cwd))
    .filter((f) => !NOT_DOCS.test(f) && existsSync(join(cwd, f)))
    .map((file) => ({ file, text: readFileSync(join(cwd, file), 'utf8') }))
    .map((d) => ({ ...d, rows: codeRows(d.text), paths: codePaths(d.text) }))
    .map((d) => ({ ...d, guide: isGuide(d.rows) }))
    .filter((d) => d.paths.length);
}

// Source files, not tests, docs, build output or config.
const CODE = /\.(js|jsx|ts|tsx|mjs|cjs|py|go|rb|java|kt|rs|php|cs|swift|scala|c|cc|cpp|cxx|h|hh|hpp|m|mm|ex|exs|erl|dart|vue|svelte|lua|zig|clj|cljs|hs|ml|fs|jl|pl|sol)$/;
// Migrations, generated code (svgr icon components in svg/), .NET test projects (src/App.Tests/), Django tests.py/test.py and dotfile configs (.eslintrc.js, .php-cs-fixer.dist.php) aren't features: nobody writes a page for them.
const NOT_CODE = /(^|\/)(tests?|Tests|Examples?|__\w+__|specs?|evals?|docs|docs_src|examples?(_\w+)?|\w+_tests?|fixtures?|vendor|vendored|bundled|third[_-]party|compiled|node_modules|dist|build|migrate|migrations?|generated|svg|benchmarks?|bench|\.[^/]+)\/|(^|\/)[^/]+\.(\w*Tests?|Specs?|Benchmarks?)(\.[^/]+)?\/|(^|\/)\.[^/]+$|\.(test|spec|d|gen|generated|min)\.\w+$|_test\.\w+$|_pb2(_grpc)?\.py$|\.pb\.go$|(^|\/)test(_[^/]*|\.c|s?\.py)$|(^|\/)conftest\.py$|^scripts\//; // top-level scripts/ is tooling

// How much of the code some doc's Code table covers, and the folders with the most uncovered files.
export function coverage(files, docs) {
  // A Docusaurus site in a subfolder (tRPC's www/) is the docs site's own code, not the product.
  const sites = files.flatMap((f) => f.match(/^(.+\/)docusaurus\.config\.\w+$/)?.[1] ?? []);
  const code = files.filter((f) => CODE.test(f) && !NOT_CODE.test(f) && !sites.some((s) => f.startsWith(s)));
  const isCovered = (f) => docs.some((d) => d.paths.some((p) => covers(p, f)));
  // Covered only by rows naming some functions (3 of a 6,500-line routing.py): counted, and reported as partial.
  const whole = (f) => docs.some((d) => (d.rows ?? d.paths.map((path) => ({ path, symbols: [] }))).some((r) => covers(r.path, f) && !r.symbols?.length));
  const gaps = new Map();
  let covered = 0, partial = 0;
  for (const f of code) {
    if (isCovered(f)) { covered++; if (!whole(f)) partial++; continue; }
    const dir = f.includes('/') ? f.slice(0, f.lastIndexOf('/') + 1) : './';
    gaps.set(dir, (gaps.get(dir) || 0) + 1);
  }
  return { total: code.length, covered, partial, gaps: [...gaps].sort((a, b) => b[1] - a[1]) };
}

// Files listed by more than one page with no symbols: any change to them flags all those pages.
export function sharedWithoutSymbols(docs) {
  const pages = new Map();
  for (const d of docs) for (const r of d.rows ?? []) {
    if (!r.symbols.length && !r.path.endsWith('/')) pages.set(r.path, [...(pages.get(r.path) ?? []), d.file]);
  }
  return [...pages].filter(([, files]) => new Set(files).size > 1);
}

// One row per lean feature doc: title, first sentence, file.
export function index(docs, dir = '') {
  const rows = docs
    .filter((d) => /^##\s+breaks when\s*$/im.test(d.text) && !isIndex(d.text))
    .map((d) => {
      const title = d.text.match(/^#\s+(.+)$/m)?.[1] ?? basename(d.file).replace(/\.mdx?$/, '');
      const lead = d.text.replace(/^---[\s\S]*?\n---\n/, '').split(/\n\s*\n/).find((p) => p.trim() && !/^\s*#/.test(p)) ?? '';
      const first = lead.replace(/\s+/g, ' ').trim().split(/(?<=[.!?])\s/)[0];
      // Links are relative to the index's folder, so pages in subfolders work.
      const link = dir && d.file.startsWith(dir + '/') ? d.file.slice(dir.length + 1) : basename(d.file);
      return `| [${title}](${link}) | ${first.replace(/\|/g, '\\|')} |`;
    })
    .sort();
  return `${INDEX_MARK}\n# Feature docs\n\n| Feature | What it does |\n|---|---|\n${rows.join('\n')}\n`;
}

// The wiki view: the same pages, rebuilt for readers who won't open the code (Confluence, Notion,
// a docs site). One source of truth stays in the repo; this is a projection, so it never drifts.
// Code tables and examples move to a "For engineers" section at the bottom; Terms become one
// glossary and every "Breaks when" table one troubleshooting page. An optional overview.md in the
// folder adds the system story and groups pages into areas.
const slug = (s) => s.toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g, '').trim().replace(/[\s_]+/g, '-') || 'area';
function splitPage(text) {
  const body = text.replace(/\r\n/g, '\n').replace(/^---\n[\s\S]*?\n---\n/, '').replace(/^\[\/\/\]: # \(.*\)\n/gm, '');
  const parts = body.split(/^(?=## )/m);
  const head = parts.shift();
  const title = head.match(/^#\s+(.+)$/m)?.[1].trim() ?? '';
  const lead = head.replace(/^#\s+.+$/m, '').trim();
  const sections = new Map(parts.map((p) => [p.match(/^##\s+(.+)/)[1].trim().toLowerCase(), p.replace(/^##.*\n/, '').trim()]));
  return { title, lead, sections };
}
const tableRows = (md) => (md || '').split('\n').filter((l) => /^\s*\|/.test(l) && !/^[\s|:-]+$/.test(l)).slice(1)
  .map((l) => l.trim().replace(/^\||\|$/g, '').split(/(?<!\\)\|/).map((c) => c.trim()));

// One line of overview.md's "## Areas": "- **Matching** (owner: Jana, payments): [Partner matching](partner-matching.md), ..."
export function areaLine(l) {
  const m = l.match(/^\s*[-*]\s+\**([^:*(]+?)\**\s*(?:\(owner:\s*([^)]+)\))?\s*:\s*(.*)$/);
  return m && { name: m[1].trim(), owner: m[2]?.trim() || null, files: [...m[3].matchAll(/\]\(([^)#]+)/g)].map((x) => basename(x[1]).replace(/\.mdx?$/, '.md')) };
}
export function wiki(docs, { source = (f) => f, repo = '', branch = 'main' } = {}) {
  const pages = docs.filter((d) => /^##\s+breaks when\s*$/im.test(d.text) && !isIndex(d.text))
    .map((d) => ({ ...splitPage(d.text), file: basename(d.file).replace(/\.mdx?$/, '.md'), src: d.file }))
    .sort((a, b) => a.title.localeCompare(b.title));
  const ov = docs.find((d) => /(^|\/)overview\.mdx?$/.test(d.file));
  const out = [];
  const known = new Map(pages.map((p) => [p.file, p.title]));
  // "see retries.md" in plain text becomes a link; Notion would otherwise turn it into a web link.
  const linkBare = (body) => body.split(/(```[\s\S]*?```|`[^`\n]*`)/).map((part, i) => (i % 2 ? part
    : part.replace(/(?<![\w(\[\/.-])([\w-]+\.md)(?![\w)\]])/g, (m, f) => (known.has(f) ? `[${known.get(f)}](${f})` : m)))).join('');
  // The hash is of the docs a page is built from, not of the output: upgrading lean-docs mustn't make
  // every published page look behind. inputs defaults to the body (pages with no single source).
  const sha = (t) => createHash('sha1').update(t).digest('hex').slice(0, 12);
  const add = (file, title, parent, body, src = null, owner = null, inputs = null) => {
    const at = src && fileUrl(repo, branch, source(src));
    const head = [repo && (src ? (/^https?:/.test(at) ? `Generated from [${source(src)}](${at}). Edit it there; changes here are overwritten.` : `Generated from \`${at}\`. Edit it there; changes here are overwritten.`) : `Generated from the docs in \`${repo}\`; changes here are overwritten.`),
      owner && `Owner: ${owner}`].filter(Boolean).join('\n\n');
    body = linkBare([head, body].filter(Boolean).join('\n\n'));
    out.push({ file, title, parent, source: src && source(src), owner, body, hash: sha(`${title}\n${owner ?? ''}\n${inputs ?? body}`) });
  };

  // Areas from the overview's "## Areas" list: "- **Intake**: [Email intake](email-intake.md), ..."
  const areas = [];
  let overview = null;
  if (ov) {
    overview = splitPage(ov.text);
    for (const l of (overview.sections.get('areas') || '').split('\n')) {
      const m = areaLine(l);
      if (m) areas.push(m);
    }
  }
  const listed = new Set(areas.flatMap((a) => a.files));
  const rest = pages.filter((p) => !listed.has(p.file));
  if (areas.length && rest.length) areas.push({ name: 'Other features', files: rest.map((p) => p.file) });
  const firstSentence = (t) => t.replace(/\s+/g, ' ').split(/(?<=[.!?])\s/)[0];
  const list = (files) => files.map((f) => pages.find((p) => p.file === f)).filter(Boolean)
    .map((p) => `- [${p.title}](${p.file}): ${firstSentence(p.lead)}`).join('\n');

  const home = overview?.title || 'Feature docs';
  let homeBody = overview ? [overview.lead, overview.sections.has('how it fits together') && `## How it fits together\n\n${overview.sections.get('how it fits together')}`].filter(Boolean).join('\n\n') : 'What each part of the system does, how it works, and what to do when it goes wrong.';
  homeBody += areas.length ? '\n\n## Areas\n\n' + areas.map((a) => `- [${a.name}](area-${slug(a.name)}.md)`).join('\n') : '\n\n## Features\n\n' + list(pages.map((p) => p.file));
  homeBody += '\n\n## Reference\n\n- [Glossary](glossary.md): the terms these pages use\n- [Troubleshooting](troubleshooting.md): every known symptom, its likely cause and what to check';
  // With areas the overview lists area names only; without, it quotes every page's opening.
  add('overview.md', home, null, homeBody, ov?.file, null, (ov?.text ?? '') + (areas.length ? '' : pages.map((p) => p.title + p.lead).join('\n')));

  for (const a of areas) add(`area-${slug(a.name)}.md`, a.name, 'overview.md', list(a.files), null, a.owner, a.files.map((f) => { const p = pages.find((x) => x.file === f); return p ? p.title + p.lead : f; }).join('\n'));
  const areaOf = (f) => areas.find((x) => x.files.includes(f));
  const parentOf = (f) => (areaOf(f) ? `area-${slug(areaOf(f).name)}.md` : 'overview.md');

  const glossary = new Map();
  for (const p of pages) {
    const s = p.sections;
    const terms = tableRows(s.get('terms'));
    for (const [term, meaning] of terms) {
      const k = term.replace(/`/g, '').toLowerCase();
      if (!glossary.has(k)) glossary.set(k, { term, meaning, pages: [] });
      glossary.get(k).pages.push(`[${p.title}](${p.file})`);
    }
    const parts = [p.lead];
    if (s.has('how it works')) parts.push(`## How it works\n\n${s.get('how it works')}`);
    if (s.has('config')) parts.push(`## Settings\n\n${s.get('config')}`);
    if (s.has('does not')) parts.push(`## Limits\n\nWhat it does not do:\n\n${s.get('does not')}`);
    if (s.has('breaks when')) parts.push(`## When something goes wrong\n\n${s.get('breaks when')}`);
    if (terms.length) parts.push(`Terms used here are explained in the [Glossary](glossary.md).`);
    const eng = [];
    if (s.has('use it')) eng.push(`How it's called:\n\n${s.get('use it')}`);
    const code = tableRows(s.get('code'));
    if (code.length) eng.push('Where it lives in the code:\n\n' + code.map(([w, what]) => `- ${w}${what ? `: ${what}` : ''}`).join('\n'));
    if (!repo) eng.push(`Source page: \`${source(p.src)}\`. Edit it there; this page is generated from it.`);
    parts.push(`## For engineers\n\n${eng.join('\n\n')}`);
    add(p.file, p.title, parentOf(p.file), parts.join('\n\n'), p.src, areaOf(p.file)?.owner, docs.find((d) => d.file === p.src).text);
  }

  const g = [...glossary.values()].sort((a, b) => a.term.replace(/`/g, '').localeCompare(b.term.replace(/`/g, ''), undefined, { sensitivity: 'base' }));
  add('glossary.md', 'Glossary', 'overview.md', g.length ? '| Term | Meaning | Used in |\n|---|---|---|\n' + g.map((t) => `| ${t.term} | ${t.meaning} | ${t.pages.join(', ')} |`).join('\n') : 'No page defines special terms.', null, null, pages.map((p) => p.title + (p.sections.get('terms') ?? '')).join('\n'));
  add('troubleshooting.md', 'Troubleshooting', 'overview.md', 'Every known symptom, grouped by feature. Each row says what you see, the likely cause, and what to check.\n\n' +
    pages.filter((p) => p.sections.has('breaks when')).map((p) => `## [${p.title}](${p.file})\n\n${p.sections.get('breaks when')}`).join('\n\n'), null, null, pages.map((p) => p.title + (p.sections.get('breaks when') ?? '')).join('\n'));
  return out;
}

// Owners from each docs folder's overview.md Areas list: { 'docs/features/x.md': 'Jana' }.
function ownersOf(cwd, docs) {
  const owners = {};
  for (const dir of new Set(docs.map((d) => dirname(d.file)))) {
    const f = join(cwd, dir, 'overview.md');
    if (!existsSync(f)) continue;
    for (const l of readFileSync(f, 'utf8').split('\n')) {
      const a = areaLine(l);
      if (a?.owner) for (const file of a.files) owners[`${dir}/${file}`] = a.owner;
    }
  }
  return owners;
}
const ownerTag = (owners, file) => (owners[file] ? ` (owner: ${owners[file]})` : '');

// The second publishing pass: once every page exists, point [x](page.md) links at the published
// pages, using the record's ids. Notion gets page mentions, other targets plain links.
// Records written by hand or by an older run may list pages as an array; accept both.
const recordPages = (rec) => (Array.isArray(rec?.pages) ? Object.fromEntries(rec.pages.map((p) => [p.file, p])) : rec?.pages ?? {});
export function relink(text, record) {
  const notionTarget = /notion/i.test(JSON.stringify(record.target ?? ''));
  const url = (r) => r.url ?? (notionTarget ? `https://www.notion.so/${String(r.id ?? r.pageId ?? r.page_id ?? '').replace(/-/g, '')}` : null);
  return text.replace(/\[([^\]]+)\]\(([\w.-]+\.md)(#[^)]*)?\)/g, (m, label, f) => {
    const r = recordPages(record)[f];
    const u = r && url(r);
    if (!u) return m;
    return notionTarget ? `<mention-page url="${u}">${label}</mention-page>` : `[${label}](${u})`;
  });
}

// A link to one file on the forge: GitHub and Gitea /blob/<branch>/, GitLab /-/blob/<branch>/, Bitbucket /src/<branch>/.
// A repo that's only a name (no web remote) gives the name and path, unlinked.
export function fileUrl(repo, branch, path) {
  if (!/^https?:\/\//.test(repo)) return `${repo}/${path}`;
  const b = encodeURIComponent(branch || 'main').replace(/%2F/g, '/');
  if (/gitlab/i.test(repo)) return `${repo}/-/blob/${b}/${path}`;
  if (/bitbucket\.org/i.test(repo)) return `${repo}/src/${b}/${path}`;
  return `${repo}/blob/${b}/${path}`;
}
function defaultBranch(cwd) {
  try { return git(['symbolic-ref', '--short', 'refs/remotes/origin/HEAD'], cwd).trim().replace(/^origin\//, ''); } catch {}
  try { return git(['rev-parse', '--abbrev-ref', 'HEAD'], cwd).trim(); } catch {}
  return 'main';
}

// Where readers find the source: the web address of origin, or the repo's name. Never a local path.
function repoName(cwd) {
  let url = '';
  try { url = git(['remote', 'get-url', 'origin'], cwd).trim().replace(/\.git$/, ''); } catch {}
  const ssh = url.match(/^git@([^:]+):(.+)$/);
  if (ssh) return `https://${ssh[1]}/${ssh[2]}`;
  if (/^https?:\/\//.test(url)) return url.replace(/\/\/[^@/]+@/, '//'); // drop any credentials
  return basename(url || cwd);
}
// Obsidian: folders are the tree, the file name is the title, [[wikilinks]] survive moving notes,
// and "For engineers" becomes a folded callout. Same pages, so the same rewrite rules apply.
const noteName = (t) => t.replace(/[\\/:*?"<>|#^[\]]/g, '-').trim();
export function obsidian(pages, { repo = '', branch = 'main' } = {}) {
  const byFile = Object.fromEntries(pages.map((p) => [p.file, p]));
  const pathOf = (p) => {
    const parent = p.parent && byFile[p.parent];
    if (p.file.startsWith('area-')) return `${noteName(p.title)}/${noteName(p.title)}.md`; // folder note
    if (parent && parent.file.startsWith('area-')) return `${noteName(parent.title)}/${noteName(p.title)}.md`;
    return `${noteName(p.title)}.md`;
  };
  return pages.map((p) => {
    let body = p.body.replace(/\[([^\]]+)\]\(([\w.-]+\.md)\)/g, (m, text, f) => {
      const t = byFile[f] && noteName(byFile[f].title);
      return !t ? m : t === text ? `[[${t}]]` : `[[${t}|${text}]]`;
    });
    body = body.replace(/^## For engineers\n\n([\s\S]*)$/m, (m, eng) => '> [!info]- For engineers\n' + eng.split('\n').map((l) => (l ? `> ${l}` : '>')).join('\n'));
    const front = ['---', p.source ? `source: "${repo ? fileUrl(repo, branch, p.source) : p.source}"` : null, 'generated-by: lean-docs', 'tags: [lean-docs]', '---'].filter(Boolean).join('\n');
    return { ...p, path: pathOf(p), body: `${front}\n\n${body}` };
  });
}

// Notion: its connector takes Notion-flavored markdown, where tables are <table> blocks, a toggle
// heading folds what's indented under it, and some characters must be escaped outside code.
// Outside code: escape Notion's markup characters, and put file names in code so Notion doesn't
// turn them into web links (.md, .py and .sh are country domains). Links are left alone.
const FILE_LIKE = /(?<![\w(\[\/.`-])((?:[\w-]+\/)*[\w-]+\.(?:mdx?|py|ts|tsx|js|mjs|sh|json|ya?ml|go|rs|rb|java|kt|cs|php|toml|ini|cfg))(?![\w\])])/g;
const notionText = (t) => t.split(/(`+[^`]*`+|\[[^\]]*\]\([^)]*\))/).map((part, i) => (i % 2 ? part
  : part.replace(/([$<>{}^~])/g, '\\$1').replace(FILE_LIKE, '`$1`'))).join('');
export function notion(pages) {
  return pages.map((p) => {
    const out = [];
    let fence = false;
    let table = null;
    const flush = () => {
      if (!table) return;
      out.push('<table header-row="true">', ...table.map((r) => `\t<tr>\n${r.map((c) => `\t\t<td>${notionText(c)}</td>`).join('\n')}\n\t</tr>`), '</table>');
      table = null;
    };
    let eng = false; // inside "For engineers": everything below is indented under the toggle heading
    for (const l of p.body.split('\n')) {
      const ind = eng && l ? '\t' : '';
      if (/^\s*(```|~~~)/.test(l)) { flush(); fence = !fence; out.push(ind + l); continue; }
      if (fence) { out.push(ind + l); continue; }
      if (/^\s*\|/.test(l)) {
        if (/^[\s|:-]+$/.test(l)) continue;
        (table ??= []).push(l.trim().replace(/^\||\|$/g, '').split(/(?<!\\)\|/).map((c) => c.trim().replace(/\\\|/g, '|')));
        continue;
      }
      flush();
      if (/^## For engineers\s*$/.test(l)) { eng = true; out.push('## For engineers {toggle="true"}'); continue; }
      out.push(ind + (/^#{1,4}\s/.test(l) ? l : notionText(l)));
    }
    flush();
    return { ...p, body: out.filter((l, i, a) => l.trim() || (a[i - 1] ?? '').trim()).join('\n') };
  });
}

// realpath: npm runs bins through a symlink.
if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  // One clear line instead of a stack trace.
  const inRepo = () => { try { return !!git(['rev-parse', '--is-inside-work-tree'], process.cwd()); } catch { return false; } };
  process.on('uncaughtException', (e) => {
    const why = e.code === 'ENOENT' && e.path ? `no such file: ${e.path}`
      : /^git /.test(e.message) ? (inRepo() ? `${e.message.split('\n')[0]}${process.argv.includes('--base') ? '. Check the --base ref.' : ''}` : 'not a git repository. Run it inside one.')
      : e.message;
    console.error(`lean-docs: ${why}`);
    process.exit(2);
  });
  const args = process.argv.slice(2);
  const flag = (name) => { const i = args.indexOf(name); return i >= 0 && !!args.splice(i, 1); };
  const option = (name) => { const i = args.indexOf(name); return i >= 0 ? args.splice(i, 2)[1] : undefined; };
  // Repo-wide commands work from the repo root, wherever they're run; paths the user types stay
  // relative to where they typed them.
  const here = process.cwd();
  const repoTop = (dir) => { try { return git(['rev-parse', '--show-toplevel'], dir).trim(); } catch { return dir; } };
  const cwd = repoTop(here);
  const fromHere = (p) => relative(cwd, resolve(here, p)).split(sep).join('/');
  const USAGE = 'usage: lean-docs [--oneline]            status of this repo\'s docs (one line for a status line or prompt)\n       lean-docs check [--root .] [--keep-shape] <doc.md>...\n       lean-docs affected [--base <ref>] [--staged [--message <file>]] [--strict]\n       lean-docs coverage [dir] [--min <pct>]\n       lean-docs index [dir]\n       lean-docs wiki [dir] [--out <dir>] [--format markdown|obsidian|notion]\n       lean-docs relink [--record <publish.json>] <file>...';
  if (['--help', '-h', 'help'].includes(args[0])) { console.log(USAGE); process.exit(0); }
  const oneline = flag('--oneline'); // for status lines and shell prompts
  const known = ['check', 'affected', 'index', 'hook', 'coverage', 'wiki', 'relink'].includes(args[0]);
  // A bare word that isn't a file is a mistyped command (`lean-docs afected`), not a page to check.
  if (!known && args[0] && /^\w+$/.test(args[0]) && !existsSync(resolve(here, args[0]))) { console.error(`lean-docs: unknown command '${args[0]}'\n${USAGE}`); process.exit(1); }
  const command = known ? args.shift() : args.length ? 'check' : 'status';
  // A typo must fail, not pass CI: `--bse HEAD~3` would otherwise run with the default base.
  const options = { check: ['--root', '--keep-shape'], affected: ['--base', '--staged', '--message', '--strict'], coverage: ['--min'], wiki: ['--out', '--format'], relink: ['--record'] }[command] ?? [];
  const unknown = args.find((a) => a.startsWith('--') && !options.includes(a));
  if (unknown) { console.error(`lean-docs: unknown option ${unknown}\n${USAGE}`); process.exit(2); }
  const dirArg = ['coverage', 'index', 'wiki'].includes(command) && args.find((a, i) => !a.startsWith('--') && !['--min', '--out', '--format', '--record'].includes(args[i - 1]));
  if (dirArg && !existsSync(resolve(here, dirArg))) { console.error(`lean-docs: no such folder: ${dirArg}`); process.exit(2); }

  if (command === 'status') {
    const docs = repoDocs(cwd).filter((d) => !isIndex(d.text));
    const c = coverage(lines(git(['ls-files', '-co', '--exclude-standard'], cwd)), docs);
    const pct = c.total ? Math.round((100 * c.covered) / c.total) : 100;
    if (!docs.length && oneline) { console.log('docs: none yet'); process.exit(0); }
    if (!docs.length) {
      const other = lines(git(['ls-files', ...DOC_GLOBS, '*.rst', '*.adoc'], cwd)).filter((f) => !NOT_DOCS.test(f) && !/(^|\/)(README|CHANGELOG|CHANGES|CONTRIBUTING|LICENSE|CODE_OF_CONDUCT|SECURITY)\.(mdx?|rst|adoc)$/i.test(f)); // Sphinx and AsciiDoc sites count as old docs
      console.log(`lean-docs: no pages yet, ${files_(c.total)} without docs.`);
      if (other.length) console.log(`  ${other.length} other doc${other.length > 1 ? 's' : ''} found (no Code tables, so nothing ties them to code). Ask "are these docs still right?" to check them,\n  or "document this repo" to write pages that use them as a source.`);
      else console.log('  Ask your agent "document this repo" (with the Claude Code plugin: /lean-docs:bootstrap).');
      process.exit(0);
    }
    const stale = affected(docs, changedFiles(cwd, {}), reviewed(cwd), differ(cwd, {}));
    const failing = docs.filter((d) => check(d.text, { root: cwd, keepShape: d.guide }).length);
    const guides = docs.filter((d) => d.guide).length;
    if (oneline) {
      const bad = [stale.length && `${stale.length} stale`, failing.length && `${failing.length} lint`].filter(Boolean);
      console.log(`docs ${pct}%${bad.length ? ' · ' + bad.join(' · ') : ' ✓'}`);
      process.exit(0);
    }
    const pages = docs.length - guides;
    console.log(`lean-docs: ${pages} page${pages !== 1 ? 's' : ''}${guides ? ` and ${guides} guide${guides > 1 ? 's' : ''}` : ''}, covering ${c.covered} of ${files_(c.total)} (${pct}%)${c.partial ? `, ${c.partial} of them in part (pages name some of their functions)` : ''}`);
    console.log(`  stale: ${stale.length ? `${stale.map((d) => d.file).join(', ')}  (lean-docs affected)` : 'none'}`);
    console.log(`  lint:  ${failing.length ? `${failing.map((d) => d.file).join(', ')}  (lean-docs check <file>)` : 'all pages pass'}`);
    if (c.gaps.length) console.log(`  next:  ${c.gaps.slice(0, 3).map(([dir, n]) => `${dir} (${n})`).join(', ')}`);
    // A generated index that no longer matches its folder: pages were added, renamed or retitled.
    const indexes = lines(git(['ls-files', '-co', '--exclude-standard', ...DOC_GLOBS], cwd))
      .filter((f) => existsSync(join(cwd, f)) && isIndex(readFileSync(join(cwd, f), 'utf8')));
    const outdated = indexes.filter((f) => {
      const dir = f.includes('/') ? f.slice(0, f.lastIndexOf('/')) : '.';
      return readFileSync(join(cwd, f), 'utf8') !== index(docs.filter((d) => d.file.startsWith(dir + '/')), dir);
    });
    if (outdated.length) console.log(`  index: ${outdated.join(', ')} is out of date  (lean-docs index <folder> > <folder>/README.md)`);
    const shared = sharedWithoutSymbols(docs);
    if (shared.length) console.log(`  noisy: ${shared.slice(0, 3).map(([f, ps]) => `${f} (${ps.length} pages)`).join(', ')}. Name the functions each page covers in its Code row.`);
    // A published wiki is a copy: say when the repo pages have moved on since the last publish.
    const recordPath = join(cwd, '.lean-docs/publish.json');
    if (existsSync(recordPath)) {
      try {
        const rec = recordPages(JSON.parse(readFileSync(recordPath, 'utf8')));
        const src = Object.values(rec).map((r) => r.source).find(Boolean);
        const dir = src ? dirname(src) : 'docs/features';
        const ov = join(cwd, dir, 'overview.md');
        const now = wiki([...docs.filter((d) => d.file.startsWith(dir + '/')), ...(existsSync(ov) ? [{ file: `${dir}/overview.md`, text: readFileSync(ov, 'utf8') }] : [])], { repo: repoName(cwd), branch: defaultBranch(cwd) });
        const behind = now.filter((p) => rec[p.file]?.hash !== p.hash).length;
        if (behind) console.log(`  wiki:  ${behind} of ${now.length} published pages are behind the docs  (/lean-docs:publish, or "publish the docs again")`);
      } catch {}
    }
    process.exit(0);
  }

  if (command === 'affected') {
    const strict = flag('--strict');
    const base = option('--base');
    const staged = flag('--staged');
    const message = option('--message'); // commit-msg hook: the message being written can carry lean-docs-ok
    const ok = new Set([...(staged ? [] : reviewed(cwd, base)), ...(message ? reviewedIn(readFileSync(message, 'utf8')) : [])]);
    const changed = changedFiles(cwd, { base, staged });
    const stale = affected(repoDocs(cwd), changed, ok, differ(cwd, { base, staged }));
    const owners = ownersOf(cwd, repoDocs(cwd));
    for (const d of byLikely(stale)) console.log(`${d.file}${ownerTag(owners, d.file)}: code it covers changed (${why(changed, d)}), the doc did not${d.likely ? '' : CHECK}`);
    if (stale.length) console.log('Update them, or if one is still right, add "lean-docs-ok: <doc>" to a commit message.');
    else {
      // Say what was compared, so an empty result can't be mistaken for "didn't run" or "nothing changed".
      const since = staged ? 'staged' : `since ${branchBase(cwd, base)?.slice(0, 12) ?? (tip(cwd) === 'HEAD' ? 'the branch point' : 'the empty tree, no commits yet')}, uncommitted included`;
      console.log(`lean-docs: no stale docs (${changed.length} changed file${changed.length === 1 ? '' : 's'}, ${since})`);
    }
    process.exit(strict && stale.length ? 1 : 0);
  }

  if (command === 'hook') {
    // Asks the agent once to update the docs its own uncommitted work made stale, before it stops.
    // Only uncommitted and untracked files count: older commits on the branch are CI's job, and an
    // agent that only answered a question must never be stopped. Each page is asked about at most
    // once per session. Never while already continuing from this hook, never on error. LEAN_DOCS_HOOK=off disables it.
    try {
      const input = JSON.parse(readFileSync(0, 'utf8') || '{}');
      if (input.stop_hook_active || process.env.LEAN_DOCS_HOOK === 'off') process.exit(0);
      const dir = repoTop(input.cwd || cwd);
      const changed = changedFiles(dir, { base: 'HEAD' });
      if (!changed.length) process.exit(0); // nothing uncommitted: skip reading the docs at all
      const seen = join(tmpdir(), `lean-docs-hook-${createHash('sha1').update(dir).digest('hex').slice(0, 12)}`);
      const [session, ...asked] = existsSync(seen) ? readFileSync(seen, 'utf8').split('\n') : [];
      const before = session === String(input.session_id) ? new Set(asked) : new Set();
      const stale = affected(repoDocs(dir), changed, new Set(), differ(dir, { base: 'HEAD' })).filter((d) => !before.has(d.file));
      if (stale.length) {
        writeFileSync(seen, [input.session_id, ...before, ...stale.map((d) => d.file)].join('\n'));
        const owners = ownersOf(dir, repoDocs(dir));
        const list = byLikely(stale).map((d) => `- ${d.file}${ownerTag(owners, d.file)} (covers ${why(changed, d)})${d.likely ? '' : CHECK}`).join('\n');
        process.stdout.write(JSON.stringify({ decision: 'block', reason:
          `lean-docs: these docs describe code you changed, but weren't updated:\n${list}\n` +
          'Read each one and fix only what your change made untrue or incomplete, keeping the rest. ' +
          'For a "check" doc, read only the lines about the function you changed. ' +
          'If a doc is still right, say so in one line. Then finish.' }));
      }
    } catch {}
    process.exit(0);
  }

  if (command === 'coverage') {
    const min = Number(option('--min') ?? 0);
    const scope = (args[0] ? fromHere(args[0]) : '').replace(/^\.\/?/, '').replace(/\/?$/, '/');
    const files = lines(git(['ls-files', '-co', '--exclude-standard'], cwd)).filter((f) => scope === '/' || f.startsWith(scope));
    const c = coverage(files, repoDocs(cwd));
    // No code files is nothing measured, not 100%: a --min gate fails on it.
    if (!c.total) { console.log(`docs cover no code files: none found${scope === '/' ? '' : ` in ${scope}`}`); process.exit(min ? 1 : 0); }
    const pct = Math.round((100 * c.covered) / c.total);
    console.log(`docs cover ${c.covered} of ${files_(c.total)}${scope === '/' ? '' : ` in ${scope}`} (${pct}%)${c.partial ? `, ${c.partial} of them in part (pages name some of their functions)` : ''}`);
    if (c.gaps.length) console.log('no docs yet, most files first:');
    for (const [dir, n] of c.gaps.slice(0, 15)) console.log(`  ${dir.padEnd(48)} ${n} file${n > 1 ? 's' : ''}`);
    if (c.gaps.length > 15) console.log(`  … and ${c.gaps.length - 15} more folders`);
    process.exit(pct < min ? 1 : 0);
  }

  if (command === 'relink') {
    const recordFile = option('--record') ?? join(relative(here, cwd) || '.', '.lean-docs/publish.json');
    const record = JSON.parse(readFileSync(resolve(here, recordFile), 'utf8'));
    let changed = 0;
    for (const f of args) {
      const before = readFileSync(resolve(here, f), 'utf8');
      const after = relink(before, record);
      if (after !== before) { writeFileSync(resolve(here, f), after); changed++; }
    }
    console.log(`lean-docs relink: ${changed} of ${args.length} files now link to the published pages`);
    process.exit(0);
  }

  if (command === 'wiki') {
    const outArg = option('--out');
    const format = option('--format') ?? 'markdown';
    if (!['markdown', 'obsidian', 'notion'].includes(format)) { console.error('lean-docs: --format is markdown, obsidian or notion'); process.exit(2); }
    const dir = fromHere(args[0] || 'docs/features').replace(/\/$/, '');
    const out = resolve(here, outArg ?? join(relative(here, cwd) || '.', '.lean-docs/wiki'));
    // The overview has no Code table, so repoDocs skips it; read it directly.
    const ovFile = ['overview.md', 'overview.mdx'].map((f) => `${dir}/${f}`).find((f) => existsSync(join(cwd, f)));
    const docs = repoDocs(cwd).filter((d) => d.file.startsWith(dir + '/'));
    const pages = wiki(ovFile ? [...docs, { file: ovFile, text: readFileSync(join(cwd, ovFile), 'utf8') }] : docs, { repo: repoName(cwd), branch: defaultBranch(cwd) });
    if (pages.length < 4) { console.error(`lean-docs: no feature pages in ${dir}`); process.exit(2); } // overview, glossary, troubleshooting + at least one
    mkdirSync(out, { recursive: true });
    if (format === 'obsidian') {
      const notes = obsidian(pages, { repo: repoName(cwd), branch: defaultBranch(cwd) });
      for (const p of notes) { mkdirSync(dirname(join(out, p.path)), { recursive: true }); writeFileSync(join(out, p.path), p.body + '\n'); }
      writeFileSync(join(out, '.lean-docs-pages.json'), JSON.stringify(notes.map(({ body, ...p }) => p), null, 2) + '\n');
    } else {
      // Notion takes the title as a property, so its files have no # line.
      for (const p of format === 'notion' ? notion(pages) : pages) writeFileSync(join(out, p.file), format === 'notion' ? p.body + '\n' : `# ${p.title}\n\n${p.body}\n`);
      writeFileSync(join(out, 'pages.json'), JSON.stringify(pages.map(({ body, ...p }) => p), null, 2) + '\n');
    }
    const shown = relative(here, out); // ponytail: absolute when it's outside, a ../../.. chain helps nobody
    const where = !shown ? '.' : shown.startsWith('..') ? out : shown;
    console.log(format === 'obsidian'
      ? `lean-docs wiki: ${pages.length} notes in ${where} (start at "${noteName(pages[0].title)}.md"; open the folder in Obsidian, or put it inside your vault)`
      : `lean-docs wiki: ${pages.length} pages in ${where} (open overview.md; pages.json gives the tree for publishing)`);
    process.exit(0);
  }

  if (command === 'index') {
    const dir = fromHere(args[0] || 'docs').replace(/\/$/, '');
    process.stdout.write(index(repoDocs(cwd).filter((d) => d.file.startsWith(dir + '/')), dir));
    process.exit(0);
  }

  const rootGiven = args.includes('--root') || args.length === 0;
  const root = option('--root') ?? (rootGiven ? cwd : undefined);
  const keepShape = flag('--keep-shape');
  // `lean-docs check` alone: every page with a Code table, checked against this repo, and every
  // guide with a lean-docs-code line, checked as a guide.
  const guides = new Set();
  if (!args.length) for (const d of repoDocs(cwd).filter((d) => !isIndex(d.text))) {
    args.push(relative(here, join(cwd, d.file)));
    if (d.guide) guides.add(args.at(-1));
  }
  if (!args.length) {
    console.error(USAGE);
    process.exit(2);
  }
  let failed = false;
  for (const file of args) {
    const text = readFileSync(file, 'utf8');
    if (isIndex(text)) continue;
    const problems = check(text, { root, keepShape: keepShape || guides.has(file), file });
    if (!problems.length) { console.log(`${file}: ok`); continue; }
    failed = true;
    console.log(`${file}: ${problems.length} problem${problems.length > 1 ? 's' : ''}`);
    for (const p of problems) console.log(`  ${p.line ? `line ${p.line}` : 'file'}: ${p.msg}`);
  }
  process.exit(failed ? 1 : 0);
}
